image: php:7.4

stages:
  - install
  - lint
  - integrate
  - deploy


install:
  stage: install
  image: composer:latest
  tags:
    - project
  before_script:
    - echo "Install Stage"
    - composer
  script:
    - composer install
  only:
    - cicd


lint:
  stage: lint
  image: composer:latest
  tags:
    - project
  before_script:
    - echo "Lint Stage"
  script:
    - composer require overtrue/phplint:^3.0 --dev -vvv
    - ./vendor/bin/phplint ./ --exclude=vendor
  only:
    - cicd


integrate:
  stage: integrate
  tags:
    - project
  before_script:
    - echo "Integrate Stage"
  script:
    - rm -r public/static
    - rm resources/views/index.blade.php
    - 'curl --location --output artifacts.zip --header "PRIVATE-TOKEN: ${TOKEN}" --request GET "https://gitlab.com/api/v4/projects/30472412/jobs/artifacts/cicd/download?job=build"'
    - unzip artifacts.zip
    - cp -r ./dist/static ./public
    - cp ./dist/index.html ../backend/resources/views/index.blade.php
  only:
    - cicd


deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - project
  before_script:
    - echo "Deploy Stage"
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$EC2_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $EC2_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $EC2_USER@$EC2_IP "/bin/bash -s " < deploy.sh
  only:
    - cicd